correctly handle `cargo +toolchain public-api` and deprecate `--toolchain` specifier
cargo-public-api/cargo-public-api pull request #113
Opened 2022-08-25 11:59 UTC by Emilgardis

2022-08-25 12:13 UTC, Emilgardis commented on rustdoc-json/src/build.rs
>              Err(BuildError::General(String::from("See above")))
Maybe this should actually be

```suggestion
        if manifest.package.is_none() && manifest.workspace.is_some() {
            Err(BuildError::VirtualManifest(options.manifest_path))
        } else {
            Err(BuildError::General(String::from("See above")))
```

2022-08-25 12:19 UTC, Emilgardis commented on rustdoc-json/src/build.rs
>              Err(BuildError::General(String::from("See above")))
fixed

2022-08-25 17:17 UTC, Enselic requested changes
Thank you so much. Looking forward to collaborate with you to get this merged. I think this change makes sense.

At first I wasn't sure if the `+` syntax was canonical, since typically `+` means a different binary will be used (e.g. nightly rustdoc vs stable rustdoc), whereas in our case the same top-level binary is always used: "cargo-public-api".

But I think this makes enough sense to go ahead with, because INDRECTLY a different `rustdoc` binary is used.

I added some comments. I am by no means all-knowledgeble, so if you think I am on the wrong track on some or all of my comments, please speak up.

Thanks again! Looking forward to getting this merged after we have sorted out the open questions!

2022-08-25 17:17 UTC, Enselic commented on cargo-public-api/src/main.rs
> +    /// [DEPRECATED]
--toolchain has not been released yet so let's just outright remove this arg on cargo-public-api instead of deprecating it

2022-08-25 17:17 UTC, Enselic commented on rustdoc-json/src/lib.rs
>      toolchain: Option<OsString>,
Hmm, I'm not sure I'm a fan of a library reading "magical" environment vars behind the scenes. What do you think about introducing an enum instead? Pseudo code:

```rust
enum Toolchain {
    FromRustupToolchainEnvVar,
    Named(OsString),
}
```

and then keep

```rust
    toolchain: Option<Toolchain>,
```

without deprecation.

that way the API surface and library behaviour and becomes clearer IMHO.

2022-08-25 17:17 UTC, Enselic commented on rustdoc-json/src/build.rs
> +        // These can override our `+nightly` with `+stable` unless we clear them
I added these lines as a fix for https://github.com/rust-lang/rustup/issues/3031#issuecomment-1181420211

However, after just one day or so the rustup folks fixed this regression and released a patch release, so the fix became obsoleted. I kept it around in case the regression would show up again.

But now I think we should just remove these three lines rather than trying to make it work with the new way to pick toolchain.

Unless you know that they are still needed?

2022-08-25 17:17 UTC, Enselic commented on rustdoc-json/src/lib.rs
> -//!            .toolchain("+nightly")
I think we want this to be `.toolchain(Toolchain::Named("+nightly"))` instead (see my other comment)

2022-08-25 17:17 UTC, Enselic commented on rustdoc-json/src/build.rs
> +        if manifest.package.is_none() && manifest.workspace.is_some() {
is this change related to removal of --toolchain? or is it some other fix?

2022-08-25 17:17 UTC, Enselic commented on .github/workflows/CI.yml
> +          override: true
How come this is needed? I'd like CI to be as similar as possible to real user machines, and they will typically not have this override

Maybe it is not needed if we add an enum as suggested in another comment?

2022-08-26 01:31 UTC, Emilgardis commented on cargo-public-api/src/main.rs
> +    /// [DEPRECATED]
awesome

2022-08-26 01:32 UTC, Emilgardis commented on rustdoc-json/src/lib.rs
>      toolchain: Option<OsString>,
Makes sense to me! I think removing the toolchain flag from public api, but keeping this is good enough

2022-08-26 01:33 UTC, Emilgardis commented on rustdoc-json/src/build.rs
> +        // These can override our `+nightly` with `+stable` unless we clear them
I wasn't sure why they were needed and kept them just because they were there, removing sounds good

2022-08-26 01:36 UTC, Emilgardis commented on rustdoc-json/src/build.rs
> +        if manifest.package.is_none() && manifest.workspace.is_some() {
It's a fix, a virtual manifest is one without a package defined. For example you can have the following `Cargo.toml`

```toml
[package]
name = "my_crate"
...

[workspace]
members = ["my_other_crate"]
```

see https://github.com/cross-rs/test-workspace/blob/main/workspace/Cargo.toml for example which has all possible alternatives (except a virtual manifest, which would be a Cargo.toml without `package`

2022-08-26 01:38 UTC, Emilgardis commented on .github/workflows/CI.yml
> +          override: true
specifying `override` makes it so the toolchain specified with `actions-rs/toolchain` get's set as the one to be used by subsequent `cargo`/`rustc`/`rustdoc` etc, it's equivalent to having a `rust-toolchain.toml` file or running `rustup override set <toolchain>`

2022-08-26 01:44 UTC, Emilgardis commented on .github/workflows/CI.yml
> +          override: true
Basically, it's to not have to do `cargo +nightly <command>` in ci, because public-api doesn't set a default now, but uses the current set rustup toolchain. This could possible be changed similarly to how `cargo-expand` does it, use specify nightly if the current toolchain is definitely not nightly. https://github.com/dtolnay/cargo-expand/blob/b8b0a9d658430b51e6142c65222cd06249b39506/src/main.rs#L57.

I can implement this behaviour, I think I actually prefer it.

2022-08-26 04:13 UTC, Enselic commented on rustdoc-json/src/build.rs
> +        if manifest.package.is_none() && manifest.workspace.is_some() {
Thanks! 

Since this code will be hit only if building rustdoc fails, and since it typically won't fail if both package and workspace is present, I think this is edge case enough to not mention in release notes and thus can piggy-back on this PR. (If we want to mention this fix in the release notes we need to split it out to a different PR since I auto-generate release notes from PR titles.)

2022-08-26 04:21 UTC, Emilgardis commented
will squash if all looks good

one comment from me as a contributor, I'd hugely recommend adding a `#[warn(...)]` for everything that is gated by ci, confusing with no clippy warns locally (and not using the script)

2022-08-26 04:46 UTC, Enselic reviewed
Thank you for the update! I did another review round and the new enum look good to me. Had some  more questions/comments though.

2022-08-26 04:46 UTC, Enselic commented on cargo-public-api/src/main.rs
> +        std::env::set_var("RUSTUP_TOOLCHAIN", "nightly");
Using `cargo-expand` as a role model makes a lot of sense, but I am a bit confused, because when I git grep in `cargo-expand` it does not seem to read `RUSTUP_TOOLCHAIN`. Do you know if it uses some helper crate for that perhaps?

2022-08-26 04:46 UTC, Enselic commented on .github/workflows/CI.yml
> +          override: true
You forgot to remove this it seems?

2022-08-26 04:46 UTC, Enselic commented on cargo-public-api/tests/cargo-public-api-bin-tests.rs
> -fn custom_toolchain() {
I'd like us to keep this test since it is important to make sure that `cargo public-api` can use a custom toolchain. Couldn't we just change invocation here to match? If it becomes a non-sensical test to test with `+nightly` I think we should also install `nightly-2022-08-15` (current `MINIMUM_RUSTDOC_JSON_VERSION`) so we can pass that instead.

2022-08-26 04:56 UTC, Emilgardis commented on cargo-public-api/tests/cargo-public-api-bin-tests.rs
> -fn custom_toolchain() {
what about

```
#[test]
#[ignore]
fn minimum_toolchain() {
	// set BuildOptions.toolchain to `nightly-2022-08-15`, do the other stuff.
}

Adding a CI test for this makes sense

2022-08-26 04:56 UTC, Emilgardis commented on .github/workflows/CI.yml
> +          override: true
It needs to be left in as the tests assume that the toolchain is changed in the code, but the toolchain is only changed in `main_` and not in the tests

2022-08-26 04:56 UTC, Emilgardis commented on cargo-public-api/src/main.rs
> +        std::env::set_var("RUSTUP_TOOLCHAIN", "nightly");
`cargo-expand` reruns itself but invoked as `rustup run nightly cargo expand` (or simply put `cargo +nightly expand`. It's not strictly needed, and setting `RUSTUP_TOOLCHAIN=nightly` achieves the same result once a rustup shim is called.

2022-08-26 13:28 UTC, Emilgardis commented on cargo-public-api/tests/cargo-public-api-bin-tests.rs
> -fn custom_toolchain() {
I opted with adding this to test-invocation-variants.sh

2022-08-26 17:13 UTC, Enselic commented on cargo-public-api/src/main.rs
> +        std::env::set_var("RUSTUP_TOOLCHAIN", "nightly");
I did a bit of a rushed review this morning since I wanted to give you some feedback before taking kids to school and going to my day job. I've done some more thinking during the day, and here is where my thoughts currently are:

My initial idea with `FromRustupToolchainEnvVar` was to let the library read `RUSTUP_TOOLCHAIN`. Shouldn't that work? I think that will allow us to get rid of the `override` in CI. In fact, the current enum is only semantically different over `Option<String>`, isn't it? `Default` = `None`, `Named(foo)` = `Some(foo)`.

Also, what is `CARGO_PUBLIC_API_NO_RUN_NIGHTLY` about?

Again, I really appreciate you working on this, and I hope you don't mind us discussing this a bit back and forth.

I'll wait with another detailed review round until we have settled these higher-level questions.

I did see your other PRs 🎉 I will take a look right away!

2022-08-26 17:17 UTC, Emilgardis commented on cargo-public-api/src/main.rs
> +        std::env::set_var("RUSTUP_TOOLCHAIN", "nightly");
Why would the library read `RUSTUP_TOOLCHAIN` ? It's already set in env, and doing `cargo +$RUSTUP_TOOLCHAIN <cmd>` just does the same thing a `cargo <cmd>`

`CARGO_PUBLIC_API_NO_RUN_NIGHTLY` is for not setting the toolchain to nightly if the current toolchain is stable, this is to make it possible to use a stable compiler with the binary. Technically not needed, as `-Z unstable-options` will always need a unstable toolchain

2022-08-26 17:21 UTC, Emilgardis commented on cargo-public-api/src/main.rs
> +        std::env::set_var("RUSTUP_TOOLCHAIN", "nightly");
> Shouldn't that work? I think that will allow us to get rid of the override in CI

Try running `cargo test` with a stable toolchain and you'll see the issue.

```
❯ cargo test
   Compiling rustdoc-json v0.3.1 (/Users/emil/workspace/cargo-public-api/rustdoc-json)
   Compiling cargo-public-api v0.14.0 (/Users/emil/workspace/cargo-public-api/cargo-public-api)
   Compiling public-api v0.15.0 (/Users/emil/workspace/cargo-public-api/public-api)
    Finished test [unoptimized + debuginfo] target(s) in 2.51s
     Running unittests src/lib.rs (target/debug/deps/cargo_public_api-cad645bec020de87)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/main.rs (target/debug/deps/cargo_public_api-fdca03bee1ae1ceb)

running 3 tests
test arg_types::tests::test_deny_added ... ok
test arg_types::tests::test_deny_changed ... ok
test arg_types::tests::test_deny_removed ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/cargo-public-api-bin-tests.rs (target/debug/deps/cargo_public_api_bin_tests-9b155849dae31082)

running 31 tests
test deny_with_invalid_arg ... ok
test deny_added_when_not_diffing ... ok
test deny_when_not_diffing ... ok
test deny_removed_when_not_diffing ... ok
test deny_changed_when_not_diffing ... ok
test deny_combination_when_not_diffing ... ok
test diff_public_items_from_files ... ok
test diff_public_items_missing_one_arg ... ok
test deny_removed_with_diff ... ok
test deny_added_with_diff ... ok
test deny_without_diff ... ok
test deny_changed_with_diff ... ok
test deny_with_diff ... ok
test diff_public_items_without_git_root ... ok
test diff_public_items_with_dirty_tree_fails ... ok
test diff_public_items_markdown ... ok
test diff_public_items ... ok
test long_help ... ok
test short_help ... ok
test diff_public_items_markdown_no_changes ... ok
test diff_public_items_detached_head ... ok
test virtual_manifest_error ... ok
test diff_public_items_with_color ... ok
test list_public_items ... ok
test diff_public_items_with_manifest_path ... ok
test list_public_items_with_lint_error ... ok
test list_public_items_markdown ... ok
test list_public_items_explicit_manifest_path ... ok
test target_arg ... ok
test list_public_items_with_color ... ok
test verbose ... ok

test result: ok. 31 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 4.62s

     Running tests/cargo-public-api-readme-tests.rs (target/debug/deps/cargo_public_api_readme_tests-3dafe32ee512dee9)

running 1 test
test installation_instructions_mentions_minimum_rustdoc_json_version ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target/debug/deps/public_api-bda5eb184e903f0e)

running 25 tests
test diff::tests::no_diff_means_empty_diff ... ok
test diff::tests::single_and_only_item_removed ... ok
test diff::tests::middle_item_added ... ok
test diff::tests::middle_item_removed ... ok
test diff::tests::single_and_only_item_added ... ok
test render::test::test_type_generic ... ok
test render::test::test_type_infer ... ok
test render::test::test_type_array ... ok
test render::test::test_type_path ... ok
test diff::tests::no_off_by_one_diff_skewing ... ok
test render::test::test_type_pointer ... ok
test render::test::test_type_pointer_mut ... ok
test render::test::test_type_primitive ... ok
test diff::tests::many_identical_items ... ok
test render::test::test_type_ref ... ok
test render::test::test_type_ref_lt ... ok
test render::test::test_type_ref_lt_mut ... ok
test render::test::test_type_ref_mut ... ok
test render::test::test_type_resolved_crate_name ... ok
test render::test::test_type_resolved_long_name ... ok
test render::test::test_type_resolved_simple ... ok
test render::test::test_type_slice ... ok
test render::test::test_type_resolved_name_crate ... ok
test render::test::test_type_tuple_empty ... ok
test render::test::test_type_tuple ... ok

test result: ok. 25 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/main.rs (target/debug/deps/public_api-67745131aabc0095)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/public-api-bin-tests.rs (target/debug/deps/public_api_bin_tests-7c1cbce8c2f73565)

running 10 tests
error: the option `Z` is only accepted on the nightly compiler
error: the option `Z` is only accepted on the nightly compiler


error: could not document `example_api`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type lib --crate-name example_api src/lib.rs -o /Users/emil/workspace/cargo-public-api/test-apis/example_api-v0.1.0/target/doc --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat -Z unstable-options --output-format json --cap-lints warn -C metadata=e7754d7af416a103 -L dependency=/Users/emil/workspace/cargo-public-api/test-apis/example_api-v0.1.0/target/debug/deps --crate-version 0.1.0` (exit status: 1)
error: could not document `example_api`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type lib --crate-name example_api src/lib.rs -o /Users/emil/workspace/cargo-public-api/test-apis/example_api-v0.2.0/target/doc --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat -Z unstable-options --output-format json --cap-lints warn -C metadata=f9e99507877cdd94 -L dependency=/Users/emil/workspace/cargo-public-api/test-apis/example_api-v0.2.0/target/debug/deps --crate-version 0.2.0` (exit status: 1)
test print_diff ... FAILED
test print_public_api_with_blanket_implementations ... FAILED
test no_args_shows_help ... ok
test long_help ... ok
test too_many_args_shows_help ... ok
test short_help ... ok
error: the option `Z` is only accepted on the nightly compiler

error: could not document `example_api`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type lib --crate-name example_api src/lib.rs -o /Users/emil/workspace/cargo-public-api/test-apis/example_api-v0.2.0/target/doc --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat -Z unstable-options --output-format json --cap-lints warn -C metadata=f9e99507877cdd94 -L dependency=/Users/emil/workspace/cargo-public-api/test-apis/example_api-v0.2.0/target/debug/deps --crate-version 0.2.0` (exit status: 1)
test print_diff_reversed ... FAILED
error: the option `Z` is only accepted on the nightly compiler

error: could not document `comprehensive_api`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type lib --crate-name comprehensive_api src/lib.rs -o /Users/emil/workspace/cargo-public-api/test-apis/comprehensive_api/target/doc --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat -Z unstable-options --output-format json --cap-lints warn -C metadata=cc391f1f93a5e47e -L dependency=/Users/emil/workspace/cargo-public-api/test-apis/comprehensive_api/target/debug/deps --extern rand=/Users/emil/workspace/cargo-public-api/test-apis/comprehensive_api/target/debug/deps/librand-c26db38e8be2dce6.rmeta --crate-version 0.1.0` (exit status: 1)
test broken_pipe ... FAILED
error: the option `Z` is only accepted on the nightly compiler

error: could not document `example_api`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type lib --crate-name example_api src/lib.rs -o /Users/emil/workspace/cargo-public-api/test-apis/example_api-v0.2.0/target/doc --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat -Z unstable-options --output-format json --cap-lints warn -C metadata=f9e99507877cdd94 -L dependency=/Users/emil/workspace/cargo-public-api/test-apis/example_api-v0.2.0/target/debug/deps --crate-version 0.2.0` (exit status: 1)
test print_no_diff ... FAILED
error: the option `Z` is only accepted on  [...]

2022-08-26 17:24 UTC, Enselic commented
> one comment from me as a contributor, I'd hugely recommend adding a #[warn(...)] for everything that is gated by ci, confusing with no clippy warns locally (and not using the script)

So far I have deliberately stayed away from enforcing lints in code, because that makes e.g. `git bisect` in a code base a nightmare. With `#[deny(...)]` at least. It _should_ be fine to have `#[warn(...)]` I guess.

I weight your input as a contributor very high, so I will add `#[warn(...)]` in the code in the near future,  and  keep `deny` in CI. I think the downside of duplicated configs and warnings during e.g. `git bisect` is smaller than the upside of having lint warnings "in-band". 

Feel free to create a PR for that too! (But you are absolutely not required to do so of course, I will do it myself as soon as I get time)

2022-08-26 17:27 UTC, Emilgardis commented
Yep, deny in code is generally bad, warn is fine though. See https://github.com/rust-unofficial/patterns/blob/main/anti_patterns/deny-warnings.md 

using deny can also make it so that consumers will fail if new lints are added and you deny on a group (like `clippy::pedantic)`

2022-08-26 18:54 UTC, Enselic commented on public-api/tests/utils/mod.rs
> -            .toolchain("+nightly")
All tests pass for me locally if we keep this as `.toolchain(Toolchain::named("+nightly"))`. But I'm not sure we need to the new `Toolchain` enum at all any longer? (See other thread.)

2022-08-26 18:54 UTC, Enselic commented on .github/workflows/CI.yml
> +          override: true
Isn't that solved by not stopping to specify `+nightly`? See other comment

2022-08-26 18:54 UTC, Enselic commented on cargo-public-api/src/main.rs
> +        std::env::set_var("RUSTUP_TOOLCHAIN", "nightly");
Ah, right, I didn't consider the effect of `RUSTUP_TOOLCHAIN` being inherited by the `cargo` process spawned from inside `rustdoc_json`. But in that case, why do we need to change the `rustdoc_json` API at all? I think it makes sense to still be able to manually specify a toolchain with the lib, because that has higher prio than `RUSTUP_TOOLCHAIN` when looking at https://rust-lang.github.io/rustup/overrides.html.

And if we do that, I wonder if it wouldn't be more elegant to pass `+nightly` as `toolchain`  from `cargo-public-api`  if `probably_stable()`, instead of setting `RUSTUP_TOOLCHAIN`?

And do we even need `probably_stable()`? Couldn't we just check if `RUSTUP_TOOLCHAIN` is `stable`?

When I run
```
cargo +nightly run  -- --manifest-path cargo-public-api/Cargo.toml
```

I get:

```
RUSTUP_TOOLCHAIN=nightly-aarch64-apple-darwin
```

in the env, and with

```
cargo run  -- --manifest-path cargo-public-api/Cargo.toml
```

I get

```
RUSTUP_TOOLCHAIN=1.63-aarch64-apple-darwin
```

Seems like we can use that instead of `probably_stable()`.

I added this in main.rs to inspect env:

```
    std::process::Command::new("env").spawn().unwrap().wait().unwrap();
```

2022-08-26 21:29 UTC, Emilgardis commented on cargo-public-api/src/main.rs
> +        std::env::set_var("RUSTUP_TOOLCHAIN", "nightly");
The problem with using `RUSTUP_TOOLCHAIN` is that it gives no real information about the version of the toolchain. `--version` or reading the `multirust-channel-manifest.toml` file is the only reliable way (and reading `multirust-channel-manifest.toml` only works on normal toolchains, not linked ones (`rustup toolchain link`))

2022-08-26 21:34 UTC, Emilgardis commented on public-api/tests/utils/mod.rs
> -            .toolchain("+nightly")
If I do this, how would one run the tests with `+nightly-2022-08-15` for example?

2022-08-26 21:44 UTC, Emilgardis commented on cargo-public-api/src/main.rs
> +        std::env::set_var("RUSTUP_TOOLCHAIN", "nightly");
> I think it makes sense to still be able to manually specify a toolchain with the lib
> ...
> And if we do that, I wonder if it wouldn't be more elegant to pass +nightly as toolchain from cargo-public-api if probably_stable(), instead of setting RUSTUP_TOOLCHAIN?

I'd then have to reintroduce the `--toolchain` flag to be able to hand it down. 

also, the overrides doc is a bit misleading here. `+toolchain` only has one effect, setting the `RUSTUP_TOOLCHAIN`

2022-08-26 22:40 UTC, Emilgardis commented on cargo-public-api/src/main.rs
> +        std::env::set_var("RUSTUP_TOOLCHAIN", "nightly");
I've readded toolchain but made it skipped by clap

2022-08-27 10:26 UTC, Emilgardis commented
One thing I could do, is set the tests

```
broken_pipe
print_diff
print_diff_reversed
print_no_diff
print_public_api
print_public_api_with_blanket_implementations
```

behind a `#[cfg_attr(not(nightly), ignore)]` by introducing a build script which does

```

use rustc_version::{version, version_meta, Channel};

fn main() {
    // Assert we haven't travelled back in time
    assert!(version().unwrap().major >= 1);

    if matches!(version_meta().unwrap().channel, Channel::Nightly | Channel::Dev) {
        println!("cargo:rustc-cfg=nightly");
    }
}
```

2022-08-27 18:49 UTC, Enselic commented
It became too complex to continue with code review comments to communicate my vision for how to solve this problem, so I wrote some code instead: https://github.com/Enselic/cargo-public-api/pull/119

Looking forward to your input!

2022-08-27 21:38 UTC, Emilgardis commented
I've revamped this a bit, I now understand what you were going for with your comments after seeing #119 and I think this should satisfy that now

2022-08-27 21:41 UTC, Emilgardis commented on public-api/tests/utils/mod.rs
> -            .toolchain("+nightly")
Answered in https://github.com/Enselic/cargo-public-api/pull/119#issuecomment-1229257047

use `RUSTDOC_JSON_OVERRIDDEN_TOOLCHAIN_HACK`

2022-08-28 09:43 UTC, Enselic commented on scripts/test-invocation-variants.sh
> +
This test also pass on origin/main. I came up with this test:

```bash
# Sanity check to make sure we can make the tool build rustdoc JSON with a
# custom toolchain via the rustup proxy mechanism (see
# https://rust-lang.github.io/rustup/concepts/index.html#how-rustup-works). The
# test uses a too old nightly toolchain, which should make the tool fail if it
# works to use that toolchain
custom_toolchain="nightly-2022-06-01"
rustup toolchain install "${custom_toolchain}"
cmd="cargo +${custom_toolchain} public-api"
echo -n "${cmd} ... "
if ${cmd} >/dev/null 2>/dev/null; then
    echo "FAIL: Using '${custom_toolchain}' to build rustdoc JSON should have failed!"
    exit 1
else
    echo "PASS"
fi
```

Not very elegant, but it fails on main but passes with this PR at least, which is an important property.

2022-08-28 10:20 UTC, Enselic reviewed
I did another review round. No big remarks. Thanks!

After comments have been addressed I think we can merge this, unless anyone of us thinks of more things to tweak.

2022-08-28 10:20 UTC, Enselic commented on cargo-public-api/src/main.rs
> +fn probably_stable() -> bool {
I like code to be close to overly documented and clear (for the benefit of new contributors), so may I propose we change to this please?

```suggestion
/// Returns true if it seems like the currently active toolchain is the stable
/// toolchain. See <https://rust-lang.github.io/rustup/overrides.html> for some
/// more info of how different toolchains can be activated.
fn active_toolchain_is_probably_stable() -> bool {
```

2022-08-28 10:20 UTC, Enselic commented on cargo-public-api/src/main.rs
> -    let args = get_args();
Thank you for getting around to get rid of the double invocation of `get_args()`. That has bugged me for a while, I just never got around fixing it.

2022-08-28 10:20 UTC, Enselic commented on rustdoc-json/src/lib.rs
> +//!            .toolchain("+nightly".to_owned())
Would be nice to somehow be able to keep the old code since it is simpler, but I couldn't figure how a good way to do that after trying quickly, so let's go with this.

2022-08-28 10:20 UTC, Enselic commented on rustdoc-json/src/build.rs
> +    /// If the toolchain is set as `None`, the current active toolchain will be used.
Can we amend the docs with this please?

```rust
    /// The currently active toolchain is typically specified by the
    /// `RUSTUP_TOOLCHAIN` environment variable, which the rustup proxy
    /// mechanism sets. See <https://rust-lang.github.io/rustup/overrides.html>
    /// for more info on how the active toolchain is determined.
```

As a side-note, if we were to make `rustdoc_json` use the rustc private crates directly, like `rustdoc` itself, we could make building rustdoc less magical, because it would not depend on rustup proxy stuff. The downside would be that it would require `rustdoc_json` to be regularly updated to match any change in rustc internals. That is an adventure for another time though.

2022-08-28 13:46 UTC, Enselic commented on scripts/test-invocation-variants.sh
> +        # # Now we are ready to run the actual tests
(You forgot to uncomment these)

2022-08-28 13:55 UTC, Emilgardis commented on scripts/test-invocation-variants.sh
> +        # # Now we are ready to run the actual tests
oops!

2022-08-28 14:21 UTC, Enselic approved these changes
Thank you! Let's merge!

I plan to make a release in the coming days. I think I'll do some minor cleanups first, like adding more elaborate --help texts to all new CLI args.

But it should not take many days for a release to happen.

Thank you again for your large batch of very useful PRs :)

2022-08-28 14:21 UTC, merged

2022-08-28 15:39 UTC, Enselic commented
Meh, who wants to wait for releases? Not me.

Released as https://github.com/Enselic/cargo-public-api/releases/tag/v0.15.0 (🥳)