Fix: Replace `-` with `_` for binary package target
cargo-public-api/cargo-public-api pull request #419
Opened 2023-05-09 22:30 UTC by frondeus

Hi! First of all, thanks for this very useful crate :)

Whenever I want to build JSON documentation for a binary with `-` in it, I get a `PathBuf` that does not point to the generated file.

This PR is fixing that and adding a new test that ensures correctness.

I am opening this as a draft because perhaps a similar solution should also be applied to other package target kinds.

2023-05-11 04:08 UTC, Enselic requested changes
Thanks a lot for taking the time to open a PR, and especially thank you for the regression test 👍 

Glad you like the project :)

Just curious: What is your use case? In what scenario do you want to list the public API for a bin?

2023-05-11 04:08 UTC, Enselic commented on rustdoc-json/src/builder.rs
>          | PackageTarget::Test(package)
Probably we should always replace - with _, regardless of PackageTarget? I think we can assume that to be the case, so please replace - with _ for all PackageTargets. You do not need to add any additional regression tests for that.

2023-05-11 04:08 UTC, Enselic commented on rustdoc-json/tests/test_crates/test_crate/Cargo.toml
> +path = "src/bin/with_hypen.rs"
If you rename the file to with-hypen.rs I think you don't need this [[bin]] section at all? Not 100% sure though. Would be nice to not have it if we don't have to.

2023-05-11 07:12 UTC, frondeus commented
> Just curious: What is your use case? In what scenario do you want to list the public API for a bin?

I am only using the rustdoc-JSON and writing a library that would provide a compile-time reflection based on the JSON output.

2023-05-18 08:05 UTC, Enselic commented
@frondeus There is no urgency of course; just wanted to check if you intend to bring this PR to the finish line?

2023-05-18 08:49 UTC, frondeus commented
Yes I do, as soon as I return from my holiday leave :)

2023-06-02 16:58 UTC, Enselic approved these changes

2023-06-02 16:58 UTC, Enselic commented
I'd like to make a release this weekend, so I've helped you take this to the finish line. I hope you didn't mind!

2023-06-02 20:42 UTC, frondeus commented
Absolutely! Thanks for your work :)

2023-06-03 05:18 UTC, merged

2023-06-03 15:14 UTC, Enselic commented
Fixed in https://crates.io/crates/rustdoc-json/0.8.6