Add context when running command fails
cargo-public-api/cargo-public-api pull request #513
Opened 2023-11-13 11:56 UTC by matthiasbeyer

Closes #512 

Please have a look.
This does not remove the transparent IO error (yet), but its a good start I guess.

2023-11-13 11:57 UTC, matthiasbeyer commented
Lets see what CI tells us... I cannot link this (have to investigate what's missing in my setup, nix things, don't mind that please :laughing: )

2023-11-13 15:48 UTC, Emilgardis commented
did this fix your error message also?

2023-11-13 16:18 UTC, Emilgardis requested changes

2023-11-13 16:18 UTC, Emilgardis commented on rustdoc-json/src/lib.rs
>      IoError(#[from] std::io::Error),
this can be removed now I think since that command call is the only usage

2023-11-13 16:19 UTC, Emilgardis commented on rustdoc-json/src/lib.rs
>      IoError(#[from] std::io::Error),
that's a breaking change though, so maybe just mark as deprecated

2023-11-13 20:00 UTC, Enselic commented on rustdoc-json/src/lib.rs
>      IoError(#[from] std::io::Error),
personally I would prefer to keep it, it is very generic and likely to be needed in the future, and I'm not sure it is worth the effort to try to deprecate it

2023-11-13 20:01 UTC, Enselic commented on rustdoc-json/src/lib.rs
> +    CannotRunCommand {
One reason CI is failing is because you need to bless this new public API

Running `./scripts/bless-expected-output-for-tests.sh` should work

2023-11-13 20:02 UTC, Enselic commented on rustdoc-json/src/lib.rs
>      IoError(#[from] std::io::Error),
...or maybe we should always convert to more descriptive error messages.... but I still think it's fine to keep around for now

2023-11-29 06:53 UTC, Enselic commented
Closing for now to keep the PR inbox clean. Of course feel free to re-open this if you resume work on it!

2023-11-29 06:53 UTC, closed without merging