Replace `rustdoc_json::Builder::verbose` with the `tracing` crate
cargo-public-api/cargo-public-api pull request #564
Opened 2024-03-29 20:43 UTC by Enselic

From previous discussions my impression is that ideally we would use the `tracing` crate for logging.

While investigating https://github.com/Enselic/cargo-public-api/issues/561 I got a good reason to improve debug logging, so I switched to `tracing`. It does add a handful of more deps, but I think it's worth it. Great logging capabilities are very nice to have.

Obviously we can add more logging later, but this is a start.

I don't think anyone is using `verbose`, so going through a deprecation cycle would be overkill. Let's just remove it but release a new 0.x.0 version directly just to be safe.

2024-03-29 22:01 UTC, Emilgardis requested changes
Nice! a minor note

2024-03-29 22:01 UTC, Emilgardis commented on cargo-public-api/src/main.rs
> +    tracing_subscriber::fmt::init();
I think the default is to log to stdout, see https://togithub.com/tokio-rs/tracing/issues/2492

should be changed to stderr via the builder

2024-04-02 05:52 UTC, Enselic commented on cargo-public-api/src/main.rs
> +    tracing_subscriber::fmt::init();
Thanks, good catch. I have now added a regression test that would have caught this mistake.

2024-04-02 10:49 UTC, Emilgardis approved these changes

2024-04-02 11:07 UTC, merged