bump rustdoc-types from 0.27.0 to 0.30.0
cargo-public-api/cargo-public-api pull request #617
Opened 2024-09-13 15:42 UTC by Billy99

rust-lang changed names of several of it's field namess which is causing issues in projects using cargo-public-api. Bumping rustdoc-types to the latest release, v0.30.0.

Fixes: #616

2024-09-13 15:46 UTC, Billy99 reviewed
Trying to help out with some grunt work, but had two questions.

2024-09-13 15:46 UTC, Billy99 commented on public-api/src/item_processor.rs
> +        // ItemEnum::OpaqueTy(_) => 26, OpaqueTy removed from rustdoc-types
`OpaqueTy` was deleted from rustdoc-types. Does `TraitAlias` move to 26 or is numbering preserved? If numbering is preserved, should this just be commented out to indicated it's been deleted or just remove the line?

2024-09-13 15:46 UTC, Billy99 commented on public-api/src/render.rs
> +            GenericBound::Use(_) => todo!(),
Need some help on what needs to be done here.

2024-09-13 17:52 UTC, Billy99 commented on public-api/src/lib.rs
> +pub const MINIMUM_NIGHTLY_RUST_VERSION: &str = "nightly-2024-09-10";
I "think" this needs to be updated? It passed CI without changing, but the rustdoc JSON format changed so guessing this needs to be bumped.

2024-09-14 04:29 UTC, Enselic requested changes
Thanks! Just had some small comments.

Once this is merged it would be great if you could go through our "how to release"-document found at https://github.com/cargo-public-api/cargo-public-api/blob/main/docs/RELEASE.md and then make a separate PR with all the changes. We'll need one PR per sub-project, in case we need to make releases to more projects than public-api.

Once each PR is merged, a maintainer is just a couple of button clicks away from making a release.

But let's get this PR merged before we take that step. (If you are interested. It would be greatly appreciated.)

2024-09-14 04:29 UTC, Enselic commented on README.md
> +| 0.37.x — 0.37.x  | nightly-2024-07-05 — nightly-2024-09-09 |
Let's simplify to this:

```suggestion
| 0.37.x           | nightly-2024-07-05 — nightly-2024-09-09 |
```

2024-09-14 04:29 UTC, Enselic commented on cargo-public-api/MINIMUM_NIGHTLY_RUST_VERSION_FOR_TESTS
> +nightly-2024-09-10
This file can be removed now. It is only needed when the version for tests is different from the minimum version for clients. (See https://github.com/cargo-public-api/cargo-public-api/blob/main/docs/RELEASE.md#bumping-minimum_nightly_rust_version.)

2024-09-14 04:29 UTC, Enselic commented on public-api/src/item_processor.rs
> +        // ItemEnum::OpaqueTy(_) => 26, OpaqueTy removed from rustdoc-types
We have a good set of regression tests. If CI passes then you (and me) can be confident that nothing is broken.

My preference would be to remove the line but keep other numbers, because:
1. git blame becomes less noisy
2. it can be useful to have holes in the numbering in the future if new stuff needs to be added in the middle

2024-09-14 04:29 UTC, Enselic commented on public-api/src/lib.rs
> +pub const MINIMUM_NIGHTLY_RUST_VERSION: &str = "nightly-2024-09-10";
Yep this should be updated. Strange that CI passed without it. I would expect tests to fail since now rustdoc-types should fail to parse the old JSON that the old nightly generates.

2024-09-14 04:29 UTC, Enselic commented on public-api/src/render.rs
> +            GenericBound::Use(_) => todo!(),
As long as CI is green we can leave it as it is. I'm too lazy (read: short of time) to figure out the syntax to trigger this code path. It might require a nightly-only rustc feature, in which case it is out of scope of this project.

If this can be triggered with stable Rust code, someone will notice and file an issue, and then we'll know how to trigger this code path, and can add a regression test.

Let's change the todo!() to be more descriptive though. Something like:

```rs
todo!("Can this code path be triggered with just stable Rust? If you hit this todo with just stable Rust, please file an issue with a minimal reproducer. Thanks!");
```

2024-09-16 00:44 UTC, Billy99 commented on public-api/src/item_processor.rs
> +        // ItemEnum::OpaqueTy(_) => 26, OpaqueTy removed from rustdoc-types
Removed.

2024-09-16 00:44 UTC, Billy99 commented on public-api/src/render.rs
> +            GenericBound::Use(_) => todo!(),
Done.

2024-09-16 00:45 UTC, Billy99 commented on README.md
> +| 0.37.x — 0.37.x  | nightly-2024-07-05 — nightly-2024-09-09 |
Done.

2024-09-16 00:45 UTC, Billy99 commented on cargo-public-api/MINIMUM_NIGHTLY_RUST_VERSION_FOR_TESTS
> +nightly-2024-09-10
File removed.

2024-09-16 04:35 UTC, Enselic approved these changes
👍 let's merge

2024-09-16 04:36 UTC, merged