Handle `TraitBoundModifier`s
cargo-public-api/cargo-public-api pull request #648
Opened 2024-11-14 11:25 UTC by smoelius

Hello. I think `TraitBoundModifier`s were not being handled correctly. The present PR is an attempt to fix that. Nits are welcome.

2024-11-14 14:07 UTC, smoelius commented
The failing tests pass for me locally. Any idea why they would fail in CI?

2024-11-14 14:58 UTC, Enselic commented
Are you using latest nightly locally?

2024-11-14 17:16 UTC, smoelius commented
An error on my part meant not all of the test files were updated. The problem should be fixed now.

2024-11-14 18:32 UTC, Enselic requested changes

2024-11-14 18:32 UTC, Enselic commented on cargo-public-api/tests/expected-output/omit-auto-derived-impls.txt
> +impl<T> core::any::Any for example_api::Struct where T: 'static + ?core::marker::Sized
rustdoc indeed renders a ? in this case, so we should too 👍 

![image](https://github.com/user-attachments/assets/99eab4ce-f5c2-425f-ab9a-d64de5d9ae79)

2024-11-14 18:32 UTC, Enselic commented on public-api/src/render.rs
> +                    TraitBoundModifier::MaybeConst => {
I think this is a nightly only feature? If so it is out of scope of this tool, since it would result in too much churn for us to support nightly features. So I think I would prefer to treat this the same way as `TraitBoundModifier::None`, but I am open to being convinced otherwise.

2024-11-14 18:32 UTC, Enselic commented on public-api/src/render.rs
> +    fn test_maybe_sized() {
Thanks for adding an additional test! I do however think this is too much of a "test how things are done" rather than a "test what the end result is", so I think I would prefer to remove it. The case is well-tested in our existing test suite, so maintaining this "implementation-detail test" is likely to be unnecessary overhead going forward. Sorry for the negativity, but I value long-term maintainability of this project high. I should probably remove the existing similar tests we have...

2024-11-14 18:32 UTC, Enselic commented
> An error on my part meant not all of the test files were updated. The problem should be fixed now.

Just a tip in case you didn't see it yet: Typically you only need to run `scripts/bless-expected-output-for-tests.sh` to update expected output for tests.

2024-11-14 18:46 UTC, Enselic commented on public-api/src/render.rs
> +                        output.push(Token::symbol("?"));
Also: Can you add an entry about this to CHANGELOG.md and public-api/CHANGELOG.md please? The same entry can be used in both files.

Then I can make a release immediately after this PR is merged.

2024-11-14 18:47 UTC, Enselic commented on public-api/src/render.rs
> +                        output.push(Token::symbol("?"));
Here is my proposal on the entry:

```
## v0.41.0
* Render `?` in front of `core::marker::Sized` if applicable.
```

2024-11-14 18:48 UTC, Enselic commented on public-api/src/render.rs
> +    fn test_maybe_sized() {
Other tests removed in https://github.com/cargo-public-api/cargo-public-api/pull/652.

2024-11-14 23:53 UTC, smoelius commented
I think I made all of the requested changed. Please let me know if I missed anything, or if you see something else.

2024-11-15 05:08 UTC, Enselic approved these changes
Looks good, thank you.

2024-11-15 05:26 UTC, merged

2024-11-15 06:35 UTC, Enselic commented
Released as https://github.com/cargo-public-api/cargo-public-api/releases/tag/v0.41.0